countryCodes = {}

countryCodes.de = {
  "AF":"Afghanistan",
  "AX":"Alandinseln",
  "AL":"Albanien",
  "DZ":"Algerien",
  "UM":"Amerikanisch-Ozeanien",
  "AS":"Amerikanisch-Samoa",
  "VI":"Amerikanische Jungferninseln",
  "AD":"Andorra","AO":"Angola",
  "AI":"Anguilla","AQ":"Antarktis",
  "AG":"Antigua und Barbuda",
  "AR":"Argentinien","AM":"Armenien",
  "AW":"Aruba","AZ":"Aserbaidschan",
  "AU":"Australien","BS":"Bahamas",
  "BH":"Bahrain",
  "BD":"Bangladesch",
  "BB":"Barbados",
  "BY":"Belarus",
  "BE":"Belgien",
  "BZ":"Belize",
  "BJ":"Benin",
  "BM":"Bermuda",
  "BT":"Bhutan",
  "BO":"Bolivien",
  "BA":"Bosnien und Herzegowina",
  "BW":"Botsuana",
  "BV":"Bouvetinsel",
  "BR":"Brasilien",
  "VG":"Britische Jungferninseln",
  "IO":"Britisches Territorium im Indischen Ozean",
  "BN":"Brunei Darussalam",
  "BG":"Bulgarien",
  "BF":"Burkina Faso",
  "BI":"Burundi",
  "CL":"Chile",
  "CN":"China",
  "CK":"Cookinseln",
  "CR":"Costa Rica",
  "CI":"C\u00f4te d\u2019Ivoire",
  "CD":"Demokratische Republik Kongo",
  "KP":"Demokratische Volksrepublik Korea",
  "DE":"Deutschland",
  "DM":"Dominica",
  "DO":"Dominikanische Republik",
  "DJ":"Dschibuti",
  "DK":"D\u00e4nemark",
  "EC":"Ecuador",
  "SV":"El Salvador",
  "ER":"Eritrea",
  "EE":"Estland",
  "FK":"Falklandinseln","FJ":"Fidschi",
  "FI":"Finnland",
  "FR":"Frankreich",
  "GF":"Franz\u00f6sisch-Guayana",
  "PF":"Franz\u00f6sisch-Polynesien",
  "TF":"Franz\u00f6sische S\u00fcd- und Antarktisgebiete",
  "FO":"F\u00e4r\u00f6er",
  "GA":"Gabun",
  "GM":"Gambia",
  "GE":"Georgien",
  "GH":"Ghana",
  "GI":"Gibraltar",
  "GD":"Grenada",
  "GR":"Griechenland",
  "GL":"Gr\u00f6nland",
  "GP":"Guadeloupe",
  "GU":"Guam",
  "GT":"Guatemala",
  "GG":"Guernsey",
  "GN":"Guinea",
  "GW":"Guinea-Bissau",
  "GY":"Guyana",
  "HT":"Haiti",
  "HM":"Heard- und McDonald-Inseln",
  "HN":"Honduras",
  "IN":"Indien",
  "ID":"Indonesien",
  "IQ":"Irak",
  "IR":"Iran",
  "IE":"Irland",
  "IS":"Island",
  "IM":"Isle of Man",
  "IL":"Israel",
  "IT":"Italien",
  "JM":"Jamaika",
  "JP":"Japan",
  "YE":"Jemen",
  "JE":"Jersey",
  "JO":"Jordanien",
  "KY":"Kaimaninseln",
  "KH":"Kambodscha",
  "CM":"Kamerun",
  "CA":"Kanada",
  "CV":"Kap Verde",
  "KZ":"Kasachstan",
  "QA":"Katar",
  "KE":"Kenia",
  "KG":"Kirgisistan",
  "KI":"Kiribati",
  "CC":"Kokosinseln",
  "CO":"Kolumbien",
  "KM":"Komoren",
  "CG":"Kongo",
  "HR":"Kroatien",
  "CU":"Kuba","KW":"Kuwait",
  "LA":"Laos",
  "LS":"Lesotho",
  "LV":"Lettland",
  "LB":"Libanon",
  "LR":"Liberia",
  "LY":"Libyen",
  "LI":"Liechtenstein",
  "LT":"Litauen",
  "LU":"Luxemburg",
  "MG":"Madagaskar",
  "MW":"Malawi",
  "MY":"Malaysia",
  "MV":"Malediven",
  "ML":"Mali",
  "MT":"Malta",
  "MA":"Marokko",
  "MH":"Marshallinseln",
  "MQ":"Martinique",
  "MR":"Mauretanien",
  "MU":"Mauritius",
  "YT":"Mayotte",
  "MK":"Mazedonien",
  "MX":"Mexiko",
  "FM":"Mikronesien",
  "MC":"Monaco",
  "MN":"Mongolei",
  "ME":"Montenegro",
  "MS":"Montserrat",
  "MZ":"Mosambik",
  "MM":"Myanmar",
  "NA":"Namibia",
  "NR":"Nauru",
  "NP":"Nepal",
  "NC":"Neukaledonien",
  "NZ":"Neuseeland",
  "NI":"Nicaragua",
  "NL":"Niederlande",
  "AN":"Niederl\u00e4ndische Antillen",
  "NE":"Niger",
  "NG":"Nigeria",
  "NU":"Niue",
  "NF":"Norfolkinsel",
  "NO":"Norwegen",
  "MP":"N\u00f6rdliche Marianen",
  "OM":"Oman",
  "TL":"Osttimor",
  "PK":"Pakistan",
  "PW":"Palau",
  "PS":"Pal\u00e4stinensische Gebiete",
  "PA":"Panama",
  "PG":"Papua-Neuguinea",
  "PY":"Paraguay",
  "PE":"Peru",
  "PH":"Philippinen",
  "PN":"Pitcairn",
  "PL":"Polen",
  "PT":"Portugal",
  "PR":"Puerto Rico",
  "KR":"Republik Korea",
  "MD":"Republik Moldau",
  "RW":"Ruanda",
  "RO":"Rum\u00e4nien",
  "RU":"Russische F\u00f6deration",
  "RE":"R\u00e9union",
  "SB":"Salomonen",
  "ZM":"Sambia",
  "WS":"Samoa",
  "SM":"San Marino",
  "SA":"Saudi-Arabien",
  "SE":"Schweden",
  "CH":"Schweiz",
  "SN":"Senegal",
  "RS":"Serbien",
  "CS":"Serbien und Montenegro",
  "SC":"Seychellen",
  "SL":"Sierra Leone",
  "ZW":"Simbabwe",
  "SG":"Singapur",
  "SK":"Slowakei",
  "SI":"Slowenien",
  "SO":"Somalia",
  "HK":"Sonderverwaltungszone Hongkong",
  "MO":"Sonderverwaltungszone Macao",
  "ES":"Spanien",
  "LK":"Sri Lanka",
  "BL":"St. Barth\u00e9lemy",
  "SH":"St. Helena",
  "KN":"St. Kitts und Nevis",
  "LC":"St. Lucia",
  "MF":"St. Martin",
  "PM":"St. Pierre und Miquelon",
  "VC":"St. Vincent und die Grenadinen",
  "SD":"Sudan",
  "SR":"Suriname",
  "SJ":"Svalbard und Jan Mayen",
  "SZ":"Swasiland",
  "SY":"Syrien",
  "ST":"S\u00e3o Tom\u00e9 und Pr\u00edncipe",
  "ZA":"S\u00fcdafrika",
  "GS":"S\u00fcdgeorgien und die S\u00fcdlichen Sandwichinseln",
  "TJ":"Tadschikistan",
  "TW":"Taiwan",
  "TZ":"Tansania",
  "TH":"Thailand",
  "TG":"Togo",
  "TK":"Tokelau",
  "TO":"Tonga",
  "TT":"Trinidad und Tobago",
  "TD":"Tschad",
  "CZ":"Tschechische Republik",
  "TN":"Tunesien",
  "TM":"Turkmenistan",
  "TC":"Turks- und Caicosinseln",
  "TV":"Tuvalu",
  "TR":"T\u00fcrkei",
  "UG":"Uganda",
  "UA":"Ukraine",
  "ZZ":"Unbekannte oder ung\u00fcltige Region",
  "HU":"Ungarn",
  "UY":"Uruguay",
  "UZ":"Usbekistan",
  "VU":"Vanuatu",
  "VA":"Vatikanstadt",
  "VE":"Venezuela",
  "AE":"Vereinigte Arabische Emirate",
  "US":"Vereinigte Staaten",
  "GB":"Vereinigtes K\u00f6nigreich",
  "VN":"Vietnam",
  "WF":"Wallis und Futuna","CX":"Weihnachtsinsel",
  "EH":"Westsahara",
  "CF":"Zentralafrikanische Republik",
  "CY":"Zypern",
  "EG":"\u00c4gypten","GQ":"\u00c4quatorialguinea",
  "ET":"\u00c4thiopien",
  "AT":"\u00d6sterreich",
  "XK": "Kosovo"
  }

countryCodes.codes = [
  "XK",
  "AF",
  "AX",
  "AL",
  "DZ",
  "UM",
  "AS",
  "VI",
  "AD",
  "AO",
  "AI",
  "AQ",
  "AG",
  "AR",
  "AM",
  "AW",
  "AZ",
  "AU",
  "BS",
  "BH",
  "BD",
  "BB",
  "BY",
  "BE",
  "BZ",
  "BJ",
  "BM",
  "BT",
  "BO",
  "BA",
  "BG",
  "BW",
  "BV",
  "BR",
  "VG",
  "IO",
  "BN",
  "BF",
  "BI",
  "CL",
  "CN",
  "CK",
  "CR",
  "CI",
  "CD",
  "KP",
  "DE",
  "DM",
  "DO",
  "DJ",
  "DK",
  "EC",
  "SV",
  "ER",
  "EE",
  "FK",
  "FJ",
  "FI",
  "FR",
  "GF",
  "PF",
  "TF",
  "FO",
  "GA",
  "GM",
  "GE",
  "GH",
  "GI",
  "GD",
  "GR",
  "GL",
  "GP",
  "GU",
  "GT",
  "GG",
  "GN",
  "GW",
  "GY",
  "HT",
  "HM",
  "HN",
  "IN",
  "ID",
  "IQ",
  "IR",
  "IE",
  "IS",
  "IM",
  "IL",
  "IT",
  "JM",
  "JP",
  "YE",
  "JE",
  "JO",
  "KY",
  "KH",
  "CM",
  "CA",
  "CV",
  "KZ",
  "QA",
  "KE",
  "KG",
  "KI",
  "CC",
  "CO",
  "KM",
  "CG",
  "HR",
  "CU",
  "KW",
  "LA",
  "LS",
  "LV",
  "LB",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MG",
  "MW",
  "MY",
  "MV",
  "ML",
  "MT",
  "MA",
  "MH",
  "MQ",
  "MR",
  "MU",
  "YT",
  "MK",
  "MX",
  "FM",
  "MC",
  "MN",
  "ME",
  "MS",
  "MZ",
  "MM",
  "NA",
  "NR",
  "NP",
  "NC",
  "NZ",
  "NI",
  "NL",
  "AN",
  "NE",
  "NG",
  "NU",
  "NF",
  "NO",
  "MP",
  "OM",
  "TL",
  "PK",
  "PW",
  "PS",
  "PA",
  "PG",
  "PY",
  "PE",
  "PH",
  "PN",
  "PL",
  "PT",
  "PR",
  "KR",
  "MD",
  "RW",
  "RO",
  "RU",
  "RE",
  "SB",
  "ZM",
  "WS",
  "SM",
  "SA",
  "SE",
  "CH",
  "SN",
  "RS",
  "CS",
  "SC",
  "SL",
  "ZW",
  "SG",
  "SK",
  "SI",
  "SO",
  "HK",
  "MO",
  "ES",
  "LK",
  "BL",
  "SH",
  "KN",
  "LC",
  "MF",
  "PM",
  "VC",
  "SD",
  "SR",
  "SJ",
  "SZ",
  "SY",
  "ST",
  "ZA",
  "GS",
  "TJ",
  "TW",
  "TZ",
  "TH",
  "TG",
  "TK",
  "TO",
  "TT",
  "TD",
  "CZ",
  "TN",
  "TM",
  "TC",
  "TV",
  "TR",
  "UG",
  "UA",
  "ZZ",
  "HU",
  "UY",
  "UZ",
  "VU",
  "VA",
  "VE",
  "AE",
  "US",
  "GB",
  "VN",
  "WF",
  "EH",
  "CF",
  "CY",
  "EG",
  "ET",
  "AT",
]

countryCodes.en = { "XK": "Kosovo", "AF":"Afghanistan","AL":"Albania","DZ":"Algeria","AS":"American Samoa","AD":"Andorra","AO":"Angola","AI":"Anguilla","AQ":"Antarctica","AG":"Antigua and Barbuda","AR":"Argentina","AM":"Armenia","AW":"Aruba","AU":"Australia","AT":"Austria","AZ":"Azerbaijan","BS":"Bahamas","BH":"Bahrain","BD":"Bangladesh","BB":"Barbados","BY":"Belarus","BE":"Belgium","BZ":"Belize","BJ":"Benin","BM":"Bermuda","BT":"Bhutan","BO":"Bolivia","BA":"Bosnia and Herzegovina","BW":"Botswana","BV":"Bouvet Island","BR":"Brazil","BQ":"British Antarctic Territory","IO":"British Indian Ocean Territory","VG":"British Virgin Islands","BN":"Brunei","BG":"Bulgaria","BF":"Burkina Faso","BI":"Burundi","KH":"Cambodia","CM":"Cameroon","CA":"Canada","CT":"Canton and Enderbury Islands","CV":"Cape Verde","KY":"Cayman Islands","CF":"Central African Republic","TD":"Chad","CL":"Chile","CN":"China","CX":"Christmas Island","CC":"Cocos [Keeling] Islands","CO":"Colombia","KM":"Comoros","CG":"Congo - Brazzaville","CD":"Congo - Kinshasa","CK":"Cook Islands","CR":"Costa Rica","HR":"Croatia","CU":"Cuba","CY":"Cyprus","CZ":"Czech Republic","CI":"C\u00f4te d\u2019Ivoire","DK":"Denmark","DJ":"Djibouti","DM":"Dominica","DO":"Dominican Republic","NQ":"Dronning Maud Land","DD":"East Germany","EC":"Ecuador","EG":"Egypt","SV":"El Salvador","GQ":"Equatorial Guinea","ER":"Eritrea","EE":"Estonia","ET":"Ethiopia","FK":"Falkland Islands","FO":"Faroe Islands","FJ":"Fiji","FI":"Finland","FR":"France","GF":"French Guiana","PF":"French Polynesia","TF":"French Southern Territories","FQ":"French Southern and Antarctic Territories","GA":"Gabon","GM":"Gambia","GE":"Georgia","DE":"Germany","GH":"Ghana","GI":"Gibraltar","GR":"Greece","GL":"Greenland","GD":"Grenada","GP":"Guadeloupe","GU":"Guam","GT":"Guatemala","GG":"Guernsey","GN":"Guinea","GW":"Guinea-Bissau","GY":"Guyana","HT":"Haiti","HM":"Heard Island and McDonald Islands","HN":"Honduras","HK":"Hong Kong SAR China","HU":"Hungary","IS":"Iceland","IN":"India","ID":"Indonesia","IR":"Iran","IQ":"Iraq","IE":"Ireland","IM":"Isle of Man","IL":"Israel","IT":"Italy","JM":"Jamaica","JP":"Japan","JE":"Jersey","JT":"Johnston Island","JO":"Jordan","KZ":"Kazakhstan","KE":"Kenya","KI":"Kiribati","KW":"Kuwait","KG":"Kyrgyzstan","LA":"Laos","LV":"Latvia","LB":"Lebanon","LS":"Lesotho","LR":"Liberia","LY":"Libya","LI":"Liechtenstein","LT":"Lithuania","LU":"Luxembourg","MO":"Macau SAR China","MK":"Macedonia","MG":"Madagascar","MW":"Malawi","MY":"Malaysia","MV":"Maldives","ML":"Mali","MT":"Malta","MH":"Marshall Islands","MQ":"Martinique","MR":"Mauritania","MU":"Mauritius","YT":"Mayotte","FX":"Metropolitan France","MX":"Mexico","FM":"Micronesia","MI":"Midway Islands","MD":"Moldova","MC":"Monaco","MN":"Mongolia","ME":"Montenegro","MS":"Montserrat","MA":"Morocco","MZ":"Mozambique","MM":"Myanmar [Burma]","NA":"Namibia","NR":"Nauru","NP":"Nepal","NL":"Netherlands","AN":"Netherlands Antilles","NT":"Neutral Zone","NC":"New Caledonia","NZ":"New Zealand","NI":"Nicaragua","NE":"Niger","NG":"Nigeria","NU":"Niue","NF":"Norfolk Island","KP":"North Korea","VD":"North Vietnam","MP":"Northern Mariana Islands","NO":"Norway","OM":"Oman","PC":"Pacific Islands Trust Territory","PK":"Pakistan","PW":"Palau","PS":"Palestinian Territories","PA":"Panama","PZ":"Panama Canal Zone","PG":"Papua New Guinea","PY":"Paraguay","YD":"People's Democratic Republic of Yemen","PE":"Peru","PH":"Philippines","PN":"Pitcairn Islands","PL":"Poland","PT":"Portugal","PR":"Puerto Rico","QA":"Qatar","RO":"Romania","RU":"Russia","RW":"Rwanda","RE":"R\u00e9union","BL":"Saint Barth\u00e9lemy","SH":"Saint Helena","KN":"Saint Kitts and Nevis","LC":"Saint Lucia","MF":"Saint Martin","PM":"Saint Pierre and Miquelon","VC":"Saint Vincent and the Grenadines","WS":"Samoa","SM":"San Marino","SA":"Saudi Arabia","SN":"Senegal","RS":"Serbia","CS":"Serbia and Montenegro","SC":"Seychelles","SL":"Sierra Leone","SG":"Singapore","SK":"Slovakia","SI":"Slovenia","SB":"Solomon Islands","SO":"Somalia","ZA":"South Africa","GS":"South Georgia and the South Sandwich Islands","KR":"South Korea","ES":"Spain","LK":"Sri Lanka","SD":"Sudan","SR":"Suriname","SJ":"Svalbard and Jan Mayen","SZ":"Swaziland","SE":"Sweden","CH":"Switzerland","SY":"Syria","ST":"S\u00e3o Tom\u00e9 and Pr\u00edncipe","TW":"Taiwan","TJ":"Tajikistan","TZ":"Tanzania","TH":"Thailand","TL":"Timor-Leste","TG":"Togo","TK":"Tokelau","TO":"Tonga","TT":"Trinidad and Tobago","TN":"Tunisia","TR":"Turkey","TM":"Turkmenistan","TC":"Turks and Caicos Islands","TV":"Tuvalu","UM":"U.S. Minor Outlying Islands","PU":"U.S. Miscellaneous Pacific Islands","VI":"U.S. Virgin Islands","UG":"Uganda","UA":"Ukraine","SU":"Union of Soviet Socialist Republics","AE":"United Arab Emirates","GB":"United Kingdom","US":"United States","ZZ":"Unknown or Invalid Region","UY":"Uruguay","UZ":"Uzbekistan","VU":"Vanuatu","VA":"Vatican City","VE":"Venezuela","VN":"Vietnam","WK":"Wake Island","WF":"Wallis and Futuna","EH":"Western Sahara","YE":"Yemen","ZM":"Zambia","ZW":"Zimbabwe","AX":"\u00c5land Islands"};

